### ISSUE TITLE
TypeError on opening project

### ISSUE THREAD

**Issue by StephanOostveen** [StevenvdSchoot/vscode-compdb#1]
Hi,

When opening VSCode (see exact versions below) I get the following output in the `Extension Host` panel, so far so good:
```
2023-06-09 12:47:24.183 [info] Extension host with pid 87042 started
2023-06-09 12:47:24.233 [info] ExtensionService#_doActivateExtension vscode.git-base, startup: true, activationEvent: '*', root cause: vscode.git
2023-06-09 12:47:24.239 [info] ExtensionService#_doActivateExtension vscode.git, startup: true, activationEvent: '*'
2023-06-09 12:47:24.260 [info] ExtensionService#_doActivateExtension vscode.github, startup: true, activationEvent: '*'
2023-06-09 12:47:24.299 [info] Eager extensions activated
2023-06-09 12:47:24.312 [info] ExtensionService#_doActivateExtension vscode.debug-auto-launch, startup: false, activationEvent: 'onStartupFinished'
2023-06-09 12:47:24.313 [info] ExtensionService#_doActivateExtension vscode.merge-conflict, startup: false, activationEvent: 'onStartupFinished'
2023-06-09 12:47:24.324 [info] ExtensionService#_doActivateExtension mcu-debug.debug-tracker-vscode, startup: false, activationEvent: 'onStartupFinished', root cause: marus25.cortex-debug
2023-06-09 12:47:24.326 [info] ExtensionService#_doActivateExtension mcu-debug.peripheral-viewer, startup: false, activationEvent: 'onStartupFinished'
2023-06-09 12:47:24.337 [info] ExtensionService#_doActivateExtension streetsidesoftware.code-spell-checker, startup: false, activationEvent: 'onStartupFinished'
2023-06-09 12:47:24.428 [info] ExtensionService#_doActivateExtension mcu-debug.memory-view, startup: false, activationEvent: 'onStartupFinished', root cause: marus25.cortex-debug
2023-06-09 12:47:24.449 [info] ExtensionService#_doActivateExtension mcu-debug.rtos-views, startup: false, activationEvent: 'onStartupFinished', root cause: marus25.cortex-debug
2023-06-09 12:47:24.457 [info] ExtensionService#_doActivateExtension vscode.github-authentication, startup: false, activationEvent: 'onAuthenticationRequest:github'
2023-06-09 12:47:24.557 [info] ExtensionService#_doActivateExtension marus25.cortex-debug, startup: false, activationEvent: 'onStartupFinished'
2023-06-09 12:47:24.591 [info] ExtensionService#_doActivateExtension vscode.microsoft-authentication, startup: false, activationEvent: 'onAuthenticationRequest:microsoft'
2023-06-09 12:47:29.776 [info] ExtensionService#_doActivateExtension vscode.emmet, startup: false, activationEvent: 'onLanguage'
```

Upon selecting a project folder containing a CMake project I get the following output:
```
2023-06-09 12:48:15.741 [info] Extension host terminating: renderer closed the MessagePort
2023-06-09 12:48:15.752 [info] Extension host with pid 87042 exiting with code 0
2023-06-09 12:48:16.819 [info] Extension host with pid 87109 started
2023-06-09 12:48:16.819 [info] Skipping acquiring lock for /home/stephan/.config/Code/User/workspaceStorage/80b4c98e447ba94cc1289dc542eb0a59.
2023-06-09 12:48:16.900 [info] ExtensionService#_doActivateExtension vscode.emmet, startup: false, activationEvent: 'onLanguage'
2023-06-09 12:48:17.019 [info] ExtensionService#_doActivateExtension vscode.git-base, startup: true, activationEvent: '*', root cause: vscode.git
2023-06-09 12:48:17.021 [info] ExtensionService#_doActivateExtension ms-vscode.cmake-tools, startup: true, activationEvent: 'workspaceContains:CMakeLists.txt'
2023-06-09 12:48:17.061 [info] ExtensionService#_doActivateExtension twxs.cmake, startup: true, activationEvent: 'workspaceContains:CMakeLists.txt', root cause: svdschoot.compdb
2023-06-09 12:48:17.062 [info] ExtensionService#_doActivateExtension llvm-vs-code-extensions.vscode-clangd, startup: true, activationEvent: 'workspaceContains:CMakeLists.txt', root cause: svdschoot.compdb
2023-06-09 12:48:17.160 [info] ExtensionService#_doActivateExtension vscode.git, startup: true, activationEvent: '*'
2023-06-09 12:48:17.194 [info] ExtensionService#_doActivateExtension vscode.github, startup: true, activationEvent: '*'
2023-06-09 12:48:17.447 [info] ExtensionService#_doActivateExtension svdschoot.compdb, startup: true, activationEvent: 'workspaceContains:CMakeLists.txt'
2023-06-09 12:48:17.831 [info] ExtensionService#_doActivateExtension vscode.github-authentication, startup: false, activationEvent: 'onAuthenticationRequest:github'
2023-06-09 12:48:17.900 [info] ExtensionService#_doActivateExtension vscode.microsoft-authentication, startup: false, activationEvent: 'onAuthenticationRequest:microsoft'
2023-06-09 12:48:18.106 [info] Eager extensions activated
2023-06-09 12:48:18.142 [info] ExtensionService#_doActivateExtension vscode.debug-auto-launch, startup: false, activationEvent: 'onStartupFinished'
2023-06-09 12:48:18.143 [info] ExtensionService#_doActivateExtension vscode.merge-conflict, startup: false, activationEvent: 'onStartupFinished'
2023-06-09 12:48:20.149 [error] TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
	at Function.all (<anonymous>)
	at WorkspaceManager.runCompDB (/home/stephan/.vscode/extensions/svdschoot.compdb-1.0.0/compdb.js:127:17)
	at #handleReconfigured (/home/stephan/.vscode/extensions/svdschoot.compdb-1.0.0/compdb.js:160:26)
```

Maybe relevant information, the project uses the `cmake-kits.json` extension to specify custom toolchain files for cross compilation and `cmake-variants.json` to specify different build options (debug/release + Macro definitions). And uses the following `settings.json`:
```
{
    "cmake.buildDirectory": "${workspaceFolder}/build-${variant:mcuConfiguration}-${variant:buildType}",
    "cmake.buildBeforeRun": true,
    "cortex-debug.openocdPath": "/home/stephan/Microchip/SoftConsole-v2021.3-7.0.0.599/openocd/bin/openocd",
    "cortex-debug.armToolchainPath": "/home/stephan/Microchip/SoftConsole-v2021.3-7.0.0.599/arm-none-eabi-gcc/bin",

    "cmake.configureOnOpen": true,
    "editor.formatOnSave": true,
    "editor.defaultFormatter": "llvm-vs-code-extensions.vscode-clangd",
    "editor.formatOnPaste": true,
    "cmake.generator": "Ninja",
    "editor.wordWrapColumn": 100,
    "editor.rulers": [100],
    "workbench.colorCustomizations": {
        "editorRuler.foreground": "#ff4081"
    },
    "editor.minimap.enabled": false,
    "cmake.copyCompileCommands": "${workspaceFolder}/compile_commands.json"
}
```

VScode version details:
```
Version: 1.79.0
Commit: b380da4ef1ee00e224a15c1d4d9793e27c2b6302
Date: 2023-06-07T14:28:44.251Z
Electron: 22.5.5
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Linux x64 6.3.5-100.fc37.x86_64
```

**Comment by StevenvdSchoot** [comment]
This issue should be fixed in version 1.0.1
